[package]
name = "obs-do"
description = "WebSocket control utility for OBS Studio"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/jonhoo/obs-do.git"
categories = ["command-line-utilities"]
keywords = ["obs", "streaming", "websocket"]

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.11", features = ["derive"] }
obws = "0.11.2"
tokio = { version = "1.29.1", features = ["full"] }
directories = "5.0.1"
